'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class ErrorPage

	''' <summary>
	''' Head1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Head1 As System.Web.UI.HtmlControls.HtmlHead

	''' <summary>
	''' form1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected form1 As System.Web.UI.HtmlControls.HtmlForm

	''' <summary>
	''' ApplicationTitle control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ApplicationTitle As System.Web.UI.WebControls.Literal

	''' <summary>
	''' InfoMessagesPanel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected InfoMessagesPanel As System.Web.UI.WebControls.Literal

	''' <summary>
	''' Table1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Table1 As System.Web.UI.WebControls.Table

	''' <summary>
	''' TableRow2 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TableRow2 As System.Web.UI.WebControls.TableRow

	''' <summary>
	''' ViewSite control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewSite As System.Web.UI.WebControls.TableCell

	''' <summary>
	''' ErrorTitleLiteral control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ErrorTitleLiteral As System.Web.UI.WebControls.Literal

	''' <summary>
	''' ErrorPanel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ErrorPanel As System.Web.UI.WebControls.Panel

	''' <summary>
	''' ApologizeMessage control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ApologizeMessage As System.Web.UI.WebControls.PlaceHolder

	''' <summary>
	''' HyperLink1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected HyperLink1 As System.Web.UI.WebControls.HyperLink

	''' <summary>
	''' NavigateToStart control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected NavigateToStart As System.Web.UI.WebControls.LinkButton

	''' <summary>
	''' Details control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Details As System.Web.UI.WebControls.Panel

	''' <summary>
	''' DetailsText control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected DetailsText As System.Web.UI.WebControls.Literal

	''' <summary>
	''' ReportForm control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ReportForm As System.Web.UI.WebControls.Panel

	''' <summary>
	''' DescriptionTextBox control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected DescriptionTextBox As System.Web.UI.WebControls.TextBox

	''' <summary>
	''' ReportButton control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ReportButton As System.Web.UI.WebControls.Button
End Class
